[config]
model = "together_ai/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free"
fallback_models = ["deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free"]
custom_model_max_tokens = 8000
[github_app]
handle_push_trigger = true
pr_commands = ["/describe", "/review",]

[pr_description]
publish_labels = true

[openai]
api_base = "https://api.together.xyz/v1"